apiVersion: v1
kind: Namespace
metadata:
  name: crossplane-system
---
apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: example-provider-secret
type: Opaque
data:
  # credentials: BASE64ENCODED_PROVIDER_CREDS
---
apiVersion: harness.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: example
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: example-provider-secret
      key: credentials
---
apiVersion: gitops.harness.crossplane.io/v1alpha1
kind: Agent
metadata:
  name: example
spec:
  forProvider:
    accountIdentifier: nYY7inrwTrqqa3r1a_-krg
    projectIdentifier: ahpoc
    orgIdentifier: Innovation
    name: gitops-agent-test
    description: 'this is a test'

  providerConfigRef:
    name: example